# Generated by Django 3.1.6 on 2021-02-08 11:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_auto_20210207_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2021, 2, 8, 11, 6, 39, 262222)),
        ),
        migrations.AlterField(
            model_name='category',
            name='updated_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2021, 2, 8, 11, 6, 39, 262222)),
        ),
    ]
