# Generated by Django 3.1.6 on 2021-02-06 14:20

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0002_category_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dxcode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosis_code', models.CharField(max_length=20, unique=True)),
                ('full_code', models.CharField(max_length=20, unique=True)),
                ('abbreviated_descrition', models.TextField(blank=True)),
                ('full_description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='categories.category')),
            ],
        ),
    ]
