# Generated by Django 3.1.6 on 2021-02-06 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dxcodes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dxcode',
            name='category_title',
            field=models.TextField(blank=True),
        ),
    ]
