# Generated by Django 3.1.6 on 2021-02-07 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dxcodes', '0002_dxcode_category_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dxcode',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
