# Generated by Django 3.1.6 on 2021-02-08 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dxcodes', '0004_auto_20210208_2111'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dxcode',
            old_name='abbreviated_descrition',
            new_name='abbreviated_description',
        ),
    ]
